---
name: DRM Health Test - Install and test packages

trigger: none
schedules:
# Run tests from Production package daily
- cron: "0 0 * * *"
  displayName: Daily midnight test of Production packages
  branches:
    include:
    - master
  always: true
pr: none

resources:
  repositories:
    - repository: acid
      type: github
      name: Accelize/acid
      endpoint: Accelize
      ref: refs/heads/v1

pool:
  vmImage: ubuntu-20.04

variables:
  # Import variable group
  - group: drmLibrary
  # Set Git branch conditional variables
  - name: repo_type
    ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
      value: 'stable'
    ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
      value: 'prerelease'

jobs:
  - template: runTestFromPkgOnEc2.yml
    parameters:
      identifier: install_and_test_packages
      description: Install and test packages
      instance_type: 'f1.4xlarge'
      repo: $(repo_type)
      config_list:
      - os_distrib: 'centos_7'
        tox_operation: '-e cpp-install,c-install,noparallel-install'
        tox_extra_option: '-m minimum'
      - os_distrib: 'ubuntu_18_04'
        tox_operation: '-e cpp-install,c-install,noparallel-install'
        tox_extra_option: '-m minimum'
        dependsOn: 'centos_7'
      - os_distrib: 'ubuntu_20_04'
        tox_operation: '-e cpp-install,c-install,noparallel-install'
        tox_extra_option: '-m minimum'
        dependsOn: 'ubuntu_18_04'
      - os_distrib: 'centos_8'
        tox_operation: '-e cpp-install,c-install,noparallel-install'
        tox_extra_option: '-m minimum'
        dependsOn: 'ubuntu_20_04'
