---
name: Health tests of DRM Library packages

trigger:
  batch: true
  branches:
    include:
      - master
      - dev
  paths:
    include:
      - deployment/azure-pipelines-test-pkg.yml
      - deployment/runTestFromPkgOnEc2.yml
      - deployment/playbook_test_pkg.yml

schedules:
# Run tests from package major branches weekly, including packages build on all OS
- cron: "0 0 * * *"
  displayName: Daily midnight test of packages
  branches:
    include:
    - master
  always: true
pr: none

resources:
  repositories:
    - repository: acid
      type: github
      name: Accelize/acid
      endpoint: Accelize

pool:
  vmImage: ubuntu-latest

variables:
  # Import variable group
  - group: drmLibrary

jobs:
  - template: runTestFromPkgOnEc2.yml
    parameters:
      instance_type: 'f1.4xlarge'
      config_list:
      - os_distrib: 'centos_7'
        tox_extra_option: '-m minimum'
