---
name: Health Test - Compile, test and package

trigger: none
schedules:
# Run tests on master branche weekly on Sundays, including packages build on all OS
- cron: "0 0 * * 0"
  displayName: Weekly build on master
  branches:
    include:
    - master
  always: true
# Run tests on dev branch weekly on Saturdays, including packages build on all OS
- cron: "0 0 * * 6"
  displayName: Weekly build on dev
  branches:
    include:
    - dev
  always: true
pr: none

resources:
  repositories:
    - repository: acid
      type: github
      name: Accelize/acid
      endpoint: Accelize
      ref: refs/heads/v1

pool:
  vmImage: ubuntu-20.04

variables:
  - group: drmLibrary

  # Allow import of python files in "deployment" dir
  - name: pythonPath
    value: $(Build.SourcesDirectory)/deployment

stages:
  - stage: compile_and_test
    displayName: Compile sources and test on hardware
    variables:
      # Set Git branch conditional variables
      ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
        meteringServer: prod
      ${{ if ne(variables['Build.SourceBranch'], 'refs/heads/master') }}:
        meteringServer: dev

    jobs:
      - template: runTestOnEc2.yml
        parameters:
          instance_type: 'f1.4xlarge'
          config_list:
          - os_distrib: 'centos_7'
            tox_mode: 'debug'
            tox_coverage: false
          - os_distrib: 'ubuntu_18_04'
            tox_mode: 'debug'
            tox_coverage: false
            dependsOn: 'centos_7'

  - stage: create_packages
    displayName: Create packages
    # Build packages only if tagged or scheduled
    dependsOn: compile_and_test
    condition: succeededOrFailed()
    jobs:
      - template: buildPackages.yml
