---
# This playbook configure agents used to run FPGA tests
# Used in the "Tests" stage of "azure-pipelines-test-pkg.yml"

- hosts: all
  become: true
  roles:
    # Install Azure agent
    - name: azure_pipeline_agent

    # Install AWS FPGA
    - name: accelize.xilinx_xrt
      vars:
        aws_fpga_install: true
        aws_fpga_src_install: /opt/aws_fpga
        xilinx_xrt_env: aws
        xilinx_xrt_install: false
        xilinx_xrt_ensure_compatible_kernel: false

