# runTestOnEc2.yml
parameters:
- name: 'distribList'
  type: string
  default: 'centos_7'
- name: 'instanceType'
  type: string
  default: 'f1.4xlarge'

jobs:
- ${{ each distrib in parameters.distribList }}: # Each linux distribution
  # Start AWS agents
  - template: agents/start.yml@acid
    parameters:
      jobName: startAgent_Aws_${{ distrib }}
      agentDescription: AWS with ${{ distrib }}
      provider: awsEc2
      image: ${{ distrib }}
      instanceType: ${{ instanceType }}
      acidDir: $(Build.SourcesDirectory)/deployment/acid
      ansiblePlaybook: $(Build.SourcesDirectory)/deployment/playbook.yml

  # Run tests on AWS agent
  - job: runTests_Aws_${{ distrib }}
    displayName: Run tests on AWS with ${{ distrib }}
    dependsOn: startAgent_Aws_${{ distrib }}
    pool:
      name: Default
      demands:  # Use previously instantiated agent
        - agent.Name -equals $(Build.DefinitionName) AWS with ${{ distrib }}
    steps:
      - script: |
          cat << EOF > $(Build.SourcesDirectory)/cred.json
          {
            "client_id": "$(clientIdAccelizeAcceleratorTest2)",
            "client_secret": "$(clientSecretAccelizeAcceleratorTest2)",

            "name__admin__":"Admin_JBL_Regression",
            "client_id__admin__":"$(clientIdAdmin)",
            "client_secret__admin__":"$(clientSecretAdmin)",

            "client_id__accelize_accelerator_test_01__":
              "$(clientIdAccelizeAcceleratorTest1)",
            "client_secret__accelize_accelerator_test_01__":
              "$(clientSecretAccelizeAcceleratorTest1)",
            "email__accelize_accelerator_test_01__":
              "$(mailAccelizeAcceleratorTest1)",

            "client_id__accelize_accelerator_test_02__":
              "$(clientIdAccelizeAcceleratorTest2)",
            "client_secret__accelize_accelerator_test_02__":
              "$(clientSecretAccelizeAcceleratorTest2)",
            "email__accelize_accelerator_test_02__":
              "$(mailAccelizeAcceleratorTest2)",

            "client_id__accelize_accelerator_test_03__":
              "$(clientIdAccelizeAcceleratorTest3)",
            "client_secret__accelize_accelerator_test_03__":
              "$(clientSecretAccelizeAcceleratorTest3)",
            "email__accelize_accelerator_test_03__":
              "$(mailAccelizeAcceleratorTest3)",

            "client_id__accelize_accelerator_test_04__":
              "$(clientIdAccelizeAcceleratorTest4)",
            "client_secret__accelize_accelerator_test_04__":
              "$(clientSecretAccelizeAcceleratorTest4)",
            "email__accelize_accelerator_test_04__":
              "$(mailAccelizeAcceleratorTest4)"
          }
          EOF
        displayName: Create Accelize credentials file

      - script: sudo -E tox -p all -e
                aws-build-debug,cpp-debug,c-debug,integration-debug,coverage-debug
                -- --cred=$(Build.SourcesDirectory)/cred.json --server=$(meteringServer) -x --artifacts_dir=$(Build.SourcesDirectory)/artifacts -k test_environment_variable
        displayName: Run tests with Tox
        env:
          CODECOV_TOKEN: $(codecovToken)
          TOX_PARALLEL_NO_SPINNER: 1
          SDK_DIR: /opt/aws_fpga/sdk

      - publish: $(Build.SourcesDirectory)/artifacts
        artifact: AWS_Artifacts_${{ distrib }}
        displayName: Publish AWS Artifacts for ${{ distrib }} tests
        condition: always()

  # Stop AWS agent
  - template: agents/stop.yml@acid
    parameters:
      jobName: stopAgent_Aws_${{ distrib }}
      provider: awsEc2
      agentDescription: AWS with ${{ distrib }}
      acidDir: $(Build.SourcesDirectory)/deployment/acid
      dependsOn: runTests_Aws_${{ distrib }}
