---
# runTestOnEc2.yml

parameters:
  instance_type: 'f1.4xlarge'
  config_list:
  - os_distrib: 'centos_7'
    tox_mode: 'release'
    tox_coverage: false
    tox_extra_option: ''

jobs:
- ${{ each config in parameters.config_list }}: # For each config
  # Start AWS agents
  - template: agents/start.yml@acid
    parameters:
      jobName: startAgent_Aws_${{ config.os_distrib }}
      agentDescription: AWS with ${{ config.os_distrib }}
      provider: awsEc2
      image: ${{ config.os_distrib }}
      instanceType: ${{ parameters.instance_type }}
      acidDir: $(Build.SourcesDirectory)/deployment/acid
      ansiblePlaybook: $(Build.SourcesDirectory)/deployment/playbook.yml
      dependsOn:
        - ${{ if config.dependsOn }}:
          - runTests_Aws_${{ config.dependsOn }}
      condition: succeededOrFailed()

  # Run tests on AWS agent
  - job: runTests_Aws_${{ config.os_distrib }}
    displayName: Run tests on AWS with ${{ config.os_distrib }}
    dependsOn:
      - startAgent_Aws_${{ config.os_distrib }}
    condition: succeededOrFailed()
    pool:
      name: Default
      demands:  # Use previously instantiated agent
        - agent.Name -equals $(Build.BuildId) $(Build.DefinitionName) AWS with ${{ config.os_distrib }}
    variables:
      ${{ if config.tox_coverage }}:
        tox_operation: aws-build-${{ config.tox_mode }},cpp-${{ config.tox_mode }},c-${{ config.tox_mode }},integration-${{ config.tox_mode }},coverage-${{ config.tox_mode }}
      ${{ if not(config.tox_coverage) }}:
        tox_operation: aws-build-${{ config.tox_mode }},cpp-${{ config.tox_mode }},c-${{ config.tox_mode }},integration-${{ config.tox_mode }}
    steps:
      - script: echo "config.tox_coverage = ${{ config.tox_coverage }}"
      - script: echo "tox_operation = $(tox_operation)"
      - script:
          cat << EOF > $(Build.SourcesDirectory)/cred.json
          {
            "client_id": "$(clientIdAccelizeAcceleratorTest2)",
            "client_secret": "$(clientSecretAccelizeAcceleratorTest2)",

            "name__admin__":"Admin_JBL_Regression",
            "client_id__admin__":"$(clientIdAdmin)",
            "client_secret__admin__":"$(clientSecretAdmin)",

            "client_id__accelize_accelerator_test_01__":
              "$(clientIdAccelizeAcceleratorTest1)",
            "client_secret__accelize_accelerator_test_01__":
              "$(clientSecretAccelizeAcceleratorTest1)",
            "email__accelize_accelerator_test_01__":
              "$(mailAccelizeAcceleratorTest1)",

            "client_id__accelize_accelerator_test_02__":
              "$(clientIdAccelizeAcceleratorTest2)",
            "client_secret__accelize_accelerator_test_02__":
              "$(clientSecretAccelizeAcceleratorTest2)",
            "email__accelize_accelerator_test_02__":
              "$(mailAccelizeAcceleratorTest2)",

            "client_id__accelize_accelerator_test_03__":
              "$(clientIdAccelizeAcceleratorTest3)",
            "client_secret__accelize_accelerator_test_03__":
              "$(clientSecretAccelizeAcceleratorTest3)",
            "email__accelize_accelerator_test_03__":
              "$(mailAccelizeAcceleratorTest3)",

            "client_id__accelize_accelerator_test_04__":
              "$(clientIdAccelizeAcceleratorTest4)",
            "client_secret__accelize_accelerator_test_04__":
              "$(clientSecretAccelizeAcceleratorTest4)",
            "email__accelize_accelerator_test_04__":
              "$(mailAccelizeAcceleratorTest4)"
          }
          EOF
        displayName: Create Accelize credentials file

      - script: sudo -E tox -p all -e $(tox_operation)
                -- --cred=$(Build.SourcesDirectory)/cred.json --server=$(meteringServer) --artifacts_dir=$(Build.SourcesDirectory)/artifacts ${{ config.tox_extra_option }} -rxs
        displayName: Run tests with Tox
        env:
          CODECOV_TOKEN: $(codecovToken)
          TOX_PARALLEL_NO_SPINNER: 1
          SDK_DIR: /opt/aws_fpga/sdk

      - publish: $(Build.SourcesDirectory)/artifacts
        artifact: AWS_Artifacts_${{ config.os_distrib }}
        displayName: Publish AWS Artifacts for ${{ config.os_distrib }} tests
        condition: always()

  # Stop AWS agent
  - template: agents/stop.yml@acid
    parameters:
      jobName: stopAgent_Aws_${{ config.os_distrib }}
      provider: awsEc2
      agentDescription: AWS with ${{ config.os_distrib }}
      acidDir: $(Build.SourcesDirectory)/deployment/acid
      dependsOn: runTests_Aws_${{ config.os_distrib }}
